### ISSUE TITLE
Markdown, literature reference and auto numbering & cross reference are not well supported

### ISSUE THREAD

**Issue by mingsu** [hughjonesd/huxtable#180]
It is a great package. Several minor issues solved will make it perfect on my use case.

I made a minimal Rmarkdown demo for several features, as shown below.

````
---
title: "test hux"
bibliography: Ref.bib
output:
  bookdown::word_document2:
    toc: no
  bookdown::html_document2:
    toc: no
  bookdown::pdf_book:
    latex_engine: xelatex
---

See Table \@ref(tab:testhux).


```{r}
require(magrittr)
require(huxtable)
options(huxtable.bookdown = T)

huxtable(col1 = 1:4,
         col2 = c("*italic*", "**bold**", "^supscript^", "~subscript~"),
         col3 = c("[ @bibkey1 ]", "[ @bibkey2; @bibkey3 ]", "@bibkey1", "@bibkey2;@bibkey3")) %>%
add_footnote(text = "*italic* **bold** ^supscript^ ~subscript~ @bibkey1 [ @bibkey2; @bibkey3 ]") %>%
set_markdown(everywhere, 2, T) %>%
set_escape_contents(everywhere, 3, F) %>%
set_caption("This is table to test hux including *italic*, **bold**, ^supscript^, ~subscript~, and also reference [ @bibkey1 ] or @bibkey2") %>%
set_label("testhux")


```


I expect that:

- markdown syntax work as normal inside the caption, table cell and the footnote, including: "*italic*", "**bold**", "^supscript^", "~subscript~", etc.
- reference can work inside the caption, table cell and footnote.
- the auto numbering and cross reference
- all these characteristic can work for at least three output format:
    - bookdown::word_document2
    - bookdown::html_document2
    - bookdown::pdf_book



````

here is the used bib file.

````
>cat Ref.bib

 @article{bibkey1,
    title       = {title 1},
    author      = {Firsta Lasta and Firstb Lastb},
    year        = 2001,
    journal     = {Journal},
    volume      = 01,
    pages       = {1--2},
    number      = 1
}

@article{bibkey2,
    title       = {title 2},
    author      = {Firsta Lasta and Firstb Lastb},
    year        = 2002,
    journal     = {Journal},
    volume      = 02,
    pages       = {1--2},
    number      = 2
}

@article{bibkey3,
    title       = {title 3},
    author      = {Firsta Lasta and Firstb Lastb},
    year        = 2003,
    journal     = {Journal},
    volume      = 03,
    pages       = {1--2},
    number      = 3
}
````

**Comment by hughjonesd** [comment]
Thanks for the example file. This is a bit of a multibug, and needs splitting up:

* Markdown in captions is a feature request (and might not be a high priority unless someone makes a PR...)
* Bibtex is also a feature request, probably. I am not sure how markdown's bibtex support works; I suspect it won't work automatically, even if you set `escape_contents` to `FALSE` for the relevant skills. I think this would be worth having *if* it can be easily done (i.e. hooking into rmarkdown at some level, rather than writing my own .bib-file parser....)
* Superscript and subscript are a different variety from the markdown I'm using (which is `commonmark`) and in particular `~~foo~~` means strikethrough. I don't think that the R commonmark package has the ability to load superscript/subscript as extensions, and we are basically limited by that. (Again, though I've implemented some basic markdown output for RTF and text, I would be crazy to try and build my own markdown parser within this package!)

**Comment by hughjonesd** [comment]
Closing, but feel free to reopen feature requests/bugs for the individual issues.
