### ISSUE TITLE
huxreg: Pass parameters to tidy 

### ISSUE THREAD

**Issue by dmenne** [hughjonesd/huxtable#43]
I noted today that my own code in broom https://github.com/tidyverse/broom/issues/282  for `nlme/lme`does not follow the current conventions for `lmer` when `tidy` is called without parameters; it returns random effects by default.

Assuming I do not change this: is it possible to pass `effects="fixed"` to huxreg?

**Comment by hughjonesd** [comment]
Hmm.
I think you should definitely change it, I guess that 90% of uses involve the fixed effects.
Aside from that... I can see three ways to deal with this:
1. Allow `tidy` data frames to be passed into huxreg, instead of model objects. This would give the user full control. Data frames from `broom::tidy()` don't have their own class (perhaps they should?) but data frames could simply be checked for the appropriate column names.
2. Add a `tidy_args = list()` argument to huxreg. The downside is that you can't then customize the arguments per-regression. 
3. Do nothing. I'm not sure how many cases there are when `tidy` takes special arguments, beyond  `conf.int`.

Overall I lean towards (1). Thoughts?

**Comment by dmenne** [comment]
1. is perfect!

**Comment by hughjonesd** [comment]
Hmm... or would be, except that `huxreg` also needs to call `glance` to get the per-regression summary statistics. I think that rules out 1... the interface would get too clunky if you had to supply both the model, and the data frame.
