### ISSUE TITLE
as_flextable adds header and extraneous spaces

### ISSUE THREAD

**Issue by bwiernik** [hughjonesd/huxtable#63]
If I use `as_flextable` to output a huxtable to Word (either directly via `quick_docx` or by embedding in an RMarkdown document), this has two unfortunate side effects:

1. `as_flextable` adds the column names as a flextable header, which flextable always adds as the first row when outputting. Considering that the default huxtable behavior is to not print column names unless specifically requested, this means that `as_flextable` and other output options don't produce matching output. As a huxtable user, I would expect `as_flextable` to not add a flextable header (because I would have already added the headers I want) or at least to have `header=FALSE` as an option.

1. `as_flextable` pads each numeric cell with spaces on the left so that all cells in a column have the same width. This annoyingly messes with formatting and requires an extra step to finalize a Word document. flextable does not produce these spaces when produced directly, so it appears to happen during the `as_flextable` conversion process. Can this be corrected?

**Comment by hughjonesd** [comment]
Regarding point 1, the issue is that `flextable::flextable` has a required `headers` argument, and it seemed weird to just use the first column for this. But there is a way round this using `delete_part`. I've added a `colnames_as_header = FALSE` argument, so the default will be similar behaviour to the rest of huxtable.

Regarding point 2, can you provide an example (in a new issue)? I think this is probably to do with number_format and/or align.

**Comment by hughjonesd** [comment]
In fact, you may find that point 2 is fixed in master by 326999c. Please check.

**Comment by bwiernik** [comment]
Yes, that's fixed.

**Comment by hughjonesd** [comment]
Great. Thanks very much for the report.
